# Get all brands.

GET http://localhost:9082/cars/api/brands

###

# Get single brand.

GET http://localhost:9082/cars/api/brands/a963294f-ee53-472c-8bdc-f6364dc59e76

###

# delete brand.

DELETE http://localhost:9082/cars/api/brands/a963294f-ee53-472c-8bdc-f6364dc59e76

###

# create or update brand

PUT http://localhost:9082/cars/api/brands/a963294f-ee53-472c-8bdc-f6364dc59e76
Content-Type: application/json

{
  "name": "BMW XL123",
  "manual": true,
  "body": "Suv"
}

###

# Get all cars.

GET http://localhost:9082/cars/api/cars


###

# Get all cars of a given brand

GET http://localhost:9082/cars/api/brands/a963294f-ee53-472c-8bdc-f6364dc59e76/cars

###

# Get a car

GET http://localhost:9082/cars/api/cars/4ddea84c-8c39-4c0a-9426-e5a5fb3ca35b

###

# Remove a car

DELETE http://localhost:9082/cars/api/cars/4ddea84c-8c39-4c0a-9426-e5a5fb3ca35b


###

PUT http://localhost:9082/cars/api/brands/a963294f-ee53-472c-8bdc-f6364dc59e76/cars/580a1cb0-2e6a-4b43-86a3-1033c9bde55b
Content-Type: application/json

{
  "horsePower": 999
}


###

GET http://localhost:9082/cars/api/cars/580a1cb0-2e6a-4b43-86a3-1033c9bde55b