# Get all brands.

GET http://localhost:9082/cars/api/brands

###

# Get single brand.

GET http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8

###

# delete brand.

DELETE http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8

###

# create a brand

PUT http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8
Content-Type: application/json

{
  "name": "BMW XL123",
  "manual": true,
  "body": "Suv"
}

###

# update a brand

PATCH http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8
Content-Type: application/json

{
  "name": "BMW XL1234567890",
  "manual": false,
  "body": "Sedan"
}

###

# Get all cars.

GET http://localhost:9082/cars/api/cars

###

# Get all cars of a given brand

GET http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8/cars

###

# Get a car

GET http://localhost:9082/cars/api/cars/dd156588-751c-4653-9642-064597b2e363

###

# Remove a car

DELETE http://localhost:9082/cars/api/cars/7b66a112-e69d-401d-bea4-d1bb9796e987


###

PUT http://localhost:9082/cars/api/brands/79fac802-30a6-4ffb-b4e1-33d8453408c8/cars/7b66a112-e69d-401d-bea4-d1bb9796e987
Content-Type: application/json

{
  "id": "7b66a112-e69d-401d-bea4-d1bb9796e987",
  "horsePower": 999
}


###

GET http://localhost:9082/cars/api/cars/580a1cb0-2e6a-4b43-86a3-1033c9bde55b


###

# Get all users.

GET http://localhost:9082/cars/api/users

###

# create user

PUT http://localhost:9082/cars/api/users/0ca05b76-9b5a-4451-98b2-3f31f1d75589
Content-Type: application/json

{
  "name": "Przemek",
  "isPolish": true
}

###

# Get user.

GET http://localhost:9082/cars/api/users/0ca05b76-9b5a-4451-98b2-3f31f1d75589